# Generated by Django 6.0 on 2026-01-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kopis_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('poster', models.URLField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('relate_url', models.CharField(blank=True, max_length=500, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'events',
                'indexes': [models.Index(fields=['kopis_id'], name='events_kopis_i_35a8b9_idx'), models.Index(fields=['title'], name='events_title_245cc9_idx')],
            },
        ),
    ]
