# Generated by Django 6.0 on 2026-01-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
