# Generated by Django 6.0 on 2026-01-13 02:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='genre',
            field=models.CharField(blank=True, default='대중음악', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ArtistMapping',
            fields=[
                ('mapping_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('raw_name', models.CharField(max_length=100, unique=True)),
                ('stage_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'artist_mapping',
                'indexes': [models.Index(fields=['raw_name'], name='artist_mapp_raw_nam_1f805d_idx')],
            },
        ),
    ]
