# Generated by Django 6.0 on 2026-01-12 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='genre',
            field=models.CharField(blank=True, default='대중음악', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
