# Generated by Django 6.0 on 2026-01-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_genre_alter_event_update_date'),
        ('events', '0002_alter_event_genre_alter_event_update_date_and_more'),
    ]

    operations = [
    ]
