# Generated by Django 6.0 on 2026-01-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_refreshtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refreshtoken',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterModelTable(
            name='refreshtoken',
            table='refresh_tokens',
        ),
    ]
