# Generated by Django 6.0 on 2026-01-08 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_url_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('reaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=10)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.post')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_reactions',
                'indexes': [models.Index(fields=['post'], name='post_reacti_post_id_3b6863_idx'), models.Index(fields=['user'], name='post_reacti_user_id_f8e0ae_idx'), models.Index(fields=['type'], name='post_reacti_type_4278a3_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='uq_post_reactions_user_post')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason_category', models.CharField(max_length=30)),
                ('reason_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'indexes': [models.Index(fields=['post'], name='reports_post_id_246508_idx'), models.Index(fields=['user'], name='reports_user_id_224fd3_idx'), models.Index(fields=['reason_category'], name='reports_reason__0a822f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='uq_reports_user_post')],
            },
        ),
    ]
