# Generated by Django 6.0 on 2026-01-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='relate_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment', 'Comment'), ('event', 'Event'), ('post_like', 'Postlike'), ('post_dislike', 'Postdislike'), ('notice', 'Notice')], default='comment', max_length=20),
        ),
    ]
